'use client';

import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen bg-black text-white selection:bg-white selection:text-black">
            <Navbar />

            {/* Dynamic Background Element */}
            <div className="fixed inset-0 pointer-events-none overflow-hidden">
                <div className="absolute bottom-[-10%] left-[-10%] w-[50%] h-[50%] bg-white/5 blur-[150px] rounded-full animate-glow" />
                <div className="absolute top-[10%] right-[-5%] w-[40%] h-[40%] bg-white/[0.02] blur-[150px] rounded-full animate-glow-delayed" />
            </div>

            <main className="relative z-10">
                {/* Page Header */}
                <section className="pt-32 pb-20 px-6 sm:px-8">
                    <div className="max-w-4xl mx-auto">
                        <div className="flex flex-col gap-6 animate-fadeInUp">
                            <div className="flex items-center gap-4">
                                <span className="w-12 h-[1px] bg-white/20"></span>
                                <span className="text-white/40 text-[10px] sm:text-xs font-mono tracking-[0.6em] uppercase">
                                    Legal Architecture
                                </span>
                            </div>
                            <h1 className="text-5xl sm:text-7xl md:text-8xl font-thin tracking-tighter uppercase leading-[0.9]">
                                Terms &<br />
                                <span className="text-white/20 italic font-light">Conditions</span>
                            </h1>
                            <p className="text-white/40 font-thin text-xs sm:text-sm tracking-[0.2em] uppercase max-w-xl leading-relaxed">
                                The governing framework for utilizing the <span className="text-white">MAKERS3D</span> platform and acquiring our industrial-grade masterpieces.
                            </p>
                        </div>
                    </div>
                </section>

                {/* Content Matrix */}
                <section className="pb-32 px-6 sm:px-8">
                    <div className="max-w-4xl mx-auto flex flex-col gap-24">

                        {/* 00. Electronic Record */}
                        <div className="relative group animate-fadeInUp" style={{ animationDelay: '200ms' }}>
                            <div className="absolute -inset-8 bg-white/[0.01] border border-white/5 rounded-[40px] -z-10 transition-all duration-700 group-hover:bg-white/[0.02] group-hover:border-white/10" />
                            <div className="space-y-6">
                                <div className="flex items-baseline gap-4">
                                    <span className="text-white/10 font-mono text-4xl">00</span>
                                    <h2 className="text-2xl sm:text-3xl font-thin tracking-[0.3em] uppercase">Electronic Record</h2>
                                </div>
                                <p className="text-white/70 font-thin text-sm sm:text-base leading-relaxed tracking-wide">
                                    This document is an electronic record in terms of the <span className="text-white font-medium">Information Technology Act, 2000</span> and rules thereunder. This record is generated by a computer system and does not require any physical or digital signatures.
                                    <br /><br />
                                    Published in accordance with Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 for access or usage of the domain <span className="text-white italic">https://makers3d.in/</span>.
                                </p>
                            </div>
                        </div>

                        {/* 01. Ownership */}
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-12 animate-fadeInUp" style={{ animationDelay: '400ms' }}>
                            <div className="md:col-span-4">
                                <div className="sticky top-32 flex flex-col gap-2">
                                    <span className="text-white/20 font-mono text-sm tracking-widest">01 / ENTITY</span>
                                    <h3 className="text-white font-thin tracking-[0.2em] uppercase border-l-2 border-white/10 pl-4 py-1">Ownership</h3>
                                </div>
                            </div>
                            <div className="md:col-span-8 space-y-6">
                                <p className="text-white/60 font-thin text-sm sm:text-base leading-relaxed tracking-wide">
                                    The Platform is owned by <span className="text-white font-medium uppercase tracking-widest">Subham Kundu</span>, with its registered office located at:
                                </p>
                                <div className="p-6 border border-white/10 bg-white/[0.02] rounded-2xl">
                                    <p className="text-white font-thin text-lg tracking-wider">
                                        Sarenga, Bankura,<br />
                                        West Bengal, 722150<br />
                                        India
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* 02. Agreement */}
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-12 animate-fadeInUp" style={{ animationDelay: '600ms' }}>
                            <div className="md:col-span-4">
                                <div className="sticky top-32 flex flex-col gap-2">
                                    <span className="text-white/20 font-mono text-sm tracking-widest">02 / BINDING</span>
                                    <h3 className="text-white font-thin tracking-[0.2em] uppercase border-l-2 border-white/10 pl-4 py-1">User Agreement</h3>
                                </div>
                            </div>
                            <div className="md:col-span-8">
                                <p className="text-white/60 font-thin text-sm sm:text-base leading-relaxed tracking-wide">
                                    Your access to and use of the Services is conditioned on your acceptance of and compliance with these Terms. By accessing or using the Platform, you agree to be bound by these Terms of Use. If you disagree with any part of the terms, then you may not access the Platform.
                                </p>
                            </div>
                        </div>

                        {/* 03. Service Usage */}
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-12 animate-fadeInUp" style={{ animationDelay: '800ms' }}>
                            <div className="md:col-span-4">
                                <div className="sticky top-32 flex flex-col gap-2">
                                    <span className="text-white/20 font-mono text-sm tracking-widest">03 / PROTOCOL</span>
                                    <h3 className="text-white font-thin tracking-[0.2em] uppercase border-l-2 border-white/10 pl-4 py-1">Code of Conduct</h3>
                                </div>
                            </div>
                            <div className="md:col-span-8 space-y-8">
                                <div className="space-y-6">
                                    {[
                                        "Accurate Interaction: You agree to provide true, accurate, and complete information during and after registration.",
                                        "Risk Assumption: Use of our Services and the Platform is solely and entirely at your own risk and discretion.",
                                        "Proprietary Integrity: All contents including design, layout, look, and graphics are proprietary to MAKERS3D. Unauthorized use may lead to legal action.",
                                        "Lawful Utilization: You agree not to use the Platform for any purpose that is unlawful, illegal, or forbidden by these Terms or Indian laws.",
                                        "Third-Party Nodes: The website may contain links to external third-party websites which are governed by their own respective policies."
                                    ].map((item, i) => (
                                        <div key={i} className="flex gap-6 group">
                                            <span className="text-white/10 font-mono text-xs pt-1">[{i + 1}]</span>
                                            <p className="text-white/40 font-thin text-sm tracking-wide group-hover:text-white/70 transition-colors">
                                                {item}
                                            </p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* 04. Liability & Jurisdiction */}
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-12 animate-fadeInUp" style={{ animationDelay: '1000ms' }}>
                            <div className="md:col-span-4">
                                <div className="sticky top-32 flex flex-col gap-2">
                                    <span className="text-white/20 font-mono text-sm tracking-widest">04 / JUSTICE</span>
                                    <h3 className="text-white font-thin tracking-[0.2em] uppercase border-l-2 border-white/10 pl-4 py-1">Jurisdiction</h3>
                                </div>
                            </div>
                            <div className="md:col-span-8 space-y-6">
                                <p className="text-white/60 font-thin text-sm sm:text-base leading-relaxed tracking-wide">
                                    These Terms shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <span className="text-white">Bankura, West Bengal</span> and surrounding judicial districts.
                                </p>
                                <div className="bg-red-500/5 border border-red-500/10 p-6 rounded-2xl">
                                    <p className="text-red-400/60 font-thin text-xs sm:text-sm tracking-wide leading-relaxed">
                                        <span className="text-red-400 font-bold uppercase tracking-widest mr-2 underline underline-offset-4">Disclaimer</span>
                                        Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this Platform for any specific purpose.
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Support Footer */}
                        <div className="pt-24 border-t border-white/10 animate-fadeInUp" style={{ animationDelay: '1200ms' }}>
                            <div className="flex flex-col items-center text-center gap-8">
                                <div className="w-px h-24 bg-gradient-to-b from-white/20 to-transparent" />
                                <div className="space-y-4">
                                    <h3 className="text-white/40 font-thin text-[10px] sm:text-xs tracking-[0.4em] uppercase">
                                        Legal Communication
                                    </h3>
                                    <a
                                        href="mailto:support@makers3d.in"
                                        className="text-white text-xl sm:text-3xl font-thin tracking-widest hover:text-white/60 transition-colors"
                                    >
                                        support@makers3d.in
                                    </a>
                                    <p className="text-white/20 text-[10px] uppercase tracking-[0.2em] mt-2">Proprietor: Subham Kundu</p>
                                </div>
                                <div className="flex gap-4">
                                    <button
                                        onClick={() => window.history.back()}
                                        className="px-10 py-4 bg-white/5 border border-white/10 text-white text-[10px] font-bold tracking-[0.4em] uppercase rounded-full hover:bg-white hover:text-black transition-all duration-500"
                                    >
                                        Accept & Close
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </section>
            </main>

            <Footer />
        </div>
    );
}
